

name: Ejecutar Scraper de FBref Playing time Big5 y Guardar CSV

on:
  schedule:
    # Se ejecuta el día 1 de cada mes a las 08:00 UTC (10:00 CEST en verano)
    - cron: '0 8 1 * *'
  workflow_dispatch:

jobs:
  scrape_and_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pandas lxml html5lib unidecode

      - name: Ejecutar script de shooting
        run: python playing_time_big5.py

      - name: Commit y Push del archivo CSV generado
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Actualizar datos de shooting (CSV) [skip ci]"
          branch: main
          file_pattern: ./data/playing_time_big5.csv
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com
          commit_author: GitHub Actions Bot <actions@github.com>
